import { createContext, useContext, useState, useEffect } from 'react';

export const translations = {
  en: {
    alerts: "Alerts",
    home: "Home",
    map: "Map",
    report: "Report",
    register: " Registration",
    loading: "Loading live alerts...",
    noAlerts: "No alerts reported yet.",
    searchPlaceholder: "Search ( Colombo, Jaffna, Kandy)...",
    searchBtn: "Search",
    fullName: "Full Name",
    email: "Email", 
    district: "Your District",
    submit: "Submit",

    mainTitle: "Hyperlocal Weather Impact & Community Alerts",
    subTitle: "Get real-time weather updates and community alerts for your area.",
    selectCity: "Select a City",
    condition: "Condition",
    windSpeed: "Wind Speed",
    regionalAlert: "Regional Alert",
    alertDesc: "Monsoon warnings may be active for coastal provinces. Check local advisories.",
    viewDetails: "View Details",

    alertsTitle: "Community Alerts",
    expiryInfo: "Alerts are automatically deleted after",
    defaultAlertTitle: "Community Report",
    daysLeftText: "days left",
    days: "days",
    loadingAlerts: "Loading live alerts...",
    noAlertsWithSeverity: "No alerts with severity yet.",
    submitReportNotice: "Submit a report to see it here.",
    autoDeletesIn: "Auto-deletes in",
    deleteReportTitle: "Delete Report?",
    deleteReportDesc: "Are you sure you want to permanently delete this community report? This action cannot be undone.",
    cancel: "Cancel",
    deleteBtn: "Delete",
    deletingBtn: "Deleting",
    districtLabel: "District",
    justNow: "Just now",
    today: "Today",
    yesterday: "1 day ago",
    daysAgo: "days ago",
    highRisk: "High Risk", // 🌟 Duplicate ඉවත් කර එකක් පමණක් ඉතිරි කළා
    mediumRisk: "Medium",
    normalRisk: "Normal",
    confirmedStatus: "Confirmed",
    pendingStatus: "Pending",
    reportsCount: "reports",
    reportsToday: "reports today",

    districtAlertTitle: "District Alert Registration",
    districtAlertSub: "Register to receive community alert emails when 3+ reports are filed in your district",
    totalRegistered: "TOTAL REGISTERED",
    activeEmails: "ACTIVE EMAILS",
    districtsCovered: "DISTRICTS COVERED",
    selectDistrictCard: "SELECT DISTRICT",
    topDistrictsTitle: "TOP REGISTERED DISTRICTS",
    
    formTitle: "Register for Alerts",
    formFullName: "FULL NAME",
    formFullNamePlaceholder: "Enter your full name",
    formEmail: "EMAIL ADDRESS",
    formEmailPlaceholder: "your@email.com",
    formDistrictLive: "DISTRICT YOU LIVE IN",
    formSelectDistrictOpt: "— Select your district —",
    formBtnRegister: "Register for Alerts",
    formPrivacyNote: "Your information is only used to send community weather alerts",

    registerTitle: "Register",
    passwordLabel: "Password (6+ chars)",
    selectDistrict: "-- Select your district --",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account? ",
    loginLink: "Login",
    errSelectCity: "Please select your city.",
    errPasswordShort: "Password must be at least 6 characters.",

    reportTitle: "Report an Alert",
    selectDistrictPlaceholder: "Select District",
    selectDistrictAlert: "Please select a district before submitting.",
    alertSeverityLabel: "ALERT SEVERITY",
    medium: "Medium",
    normal: "Normal",
    locationLabel: "Location",
    descriptionLabel: "Description",
    uploadImageLabel: "Upload Image (optional)",
    selectedPoint: "Selected Point",
    submittingText: "Submitting...",
    submitBtnText: "Submit Alert",
    mapInstruction: "Click on the map to mark the exact spot:",
    reportingForDistrict: "Reporting for",
    districtText: "District",
    alertsText: "alerts",
    alertProgress: "Alert Progress",
    alertsToday: "alerts today",
    moreToTrigger: "more to trigger email",
    oneMoreAlertWarning: "One more alert in this district will trigger an email to all registered residents!",
    submitSuccess: "Alert submitted successfully! Thank you for helping your community.",
    emailSentTitle: "Community Alert Emails Sent!",
    registeredResidents: "registered resident(s) in",
    emailSentDesc: "have been notified about this alert cluster.",
    somethingWrong: "Something went wrong! Please try again."
  },
  si: {
    alerts: "ප්‍රජා අනතුරු ඇඟවීම්",
    home: "මුල් පිටුව",
    map: "සිතියම",
    report: "අනතුරක් වාර්තා කරන්න",
    register: "දිස්ත්‍රික් ලියාපදිංචිය",
    loading: "සජීවී දත්ත ලබා ගනිමින් පවතී...",
    noAlerts: "තවමත් අනතුරු ඇඟවීම් කිසිවක් වාර්තා වී නොමැත.",
    searchPlaceholder: "සොයන්න (කොළඹ, යාපනය, මහනුවර)...",
    searchBtn: "සොයන්න",
    fullName: "සම්පූර්ණ නම",
    email: "ඊමේල් ලිපිනය", 
    district: "ඔබේ දිස්ත්‍රික්කය",
    submit: "ඇතුළත් කරන්න",
    mainTitle: "ප්‍රාදේශීය කාලගුණ බලපෑම් සහ ප්‍රජා අනතුරු ඇඟවීම්",
    subTitle: "ඔබේ ප්‍රදේශය සඳහා සජීවී කාලගුණ යාවත්කාලීන කිරීම් සහ අනතුරු ඇඟවීම් ලබා ගන්න.",
    selectCity: "නගරයක් තෝරන්න",
    condition: "තත්ත්වය",
    windSpeed: "සුළඟේ වේගය",
    regionalAlert: "ප්‍රාදේශීය අනතුරු ඇඟවීම්",
    alertDesc: "වෙරළබඩ පළාත් සඳහා මෝසම් අනතුරු ඇඟවීම් සක්‍රීය විය හැක. දේශීය උපදෙස් පරීක්ෂා කරන්න.",
    viewDetails: "විස්තර බලන්න",

    alertsTitle: "ප්‍රජා දැනුම්දීම්",
    defaultAlertTitle: "ප්‍රජා වාර්තාව",
    daysLeftText: "දිනකින්",
    expiryInfo: "දැනුම්දීම් ස්වයංක්‍රීයව මැකී යන්නේ දින",
    days: "කට පසුවයි",
    loadingAlerts: "දැනුම්දීම් සක්‍රීය කරමින්...",
    noAlertsWithSeverity: "මෙම අවදානම් මට්ටමේ දැනුම්දීම් කිසිවක් නැත.",
    submitReportNotice: "එය මෙතැනින් දැකීමට වාර්තාවක් ඉදිරිපත් කරන්න.",
    autoDeletesIn: "ස්වයංක්‍රීයව මැකී යාමට තව",
    deleteReportTitle: "වාර්තාව මකා දමන්නද?",
    deleteReportDesc: "මෙම ප්‍රජා වාර්තාව ස්ථිරවම මකා දැමීමට ඔබට විශ්වාසද? මෙම ක්‍රියාව ආපසු හැරවිය නොහැක.",
    cancel: "අවලංගු කරන්න",
    deleteBtn: "මකන්න",
    deletingBtn: "මකමින්...",
    districtLabel: "දිස්ත්‍රික්කය",
    justNow: "දැන් ලැබුණා",
    today: "අද",
    yesterday: "ඊයේ",
    daysAgo: "දිනවලට පෙර",
    highRisk: "ඉහළ අවදානමක්", // 🌟 Duplicate ඉවත් කළා
    mediumRisk: "මධ්‍යම අවදානමක්",
    normalRisk: "සාමාන්‍ය තත්ත්වයක්",
    confirmedStatus: "තහවුරු කරන ලදී",
    pendingStatus: "පරීක්ෂණ මට්ටමේ",
    reportsCount: "වාර්තා",
    reportsToday: "අද වාර්තා",

    districtAlertTitle: "දිස්ත්‍රික් අනතුරු ඇඟවීම් ලියාපදිංචිය",
    districtAlertSub: "ඔබේ දිස්ත්‍රික්කයෙන් වාර්තා 3ක් හෝ වැඩි ගණනක් ලැබුණු විට අනතුරු ඇඟවීමේ ඊමේල් ලබා ගැනීමට ලියාපදිංචි වන්න",
    totalRegistered: "මුළු ලියාපදිංචි ගණන",
    activeEmails: "සක්‍රීය ඊමේල් ලිපිනයන්",
    districtsCovered: "ආවරණය කර ඇති දිස්ත්‍රික්ක",
    selectDistrictCard: "දිස්ත්‍රික්කය තෝරන්න",
    topDistrictsTitle: "වැඩිම ලියාපදිංචි දිස්ත්‍රික්ක",
    
    formTitle: "අනතුරු ඇඟවීම් සඳහා ලියාපදිංචි වන්න",
    formFullName: "සම්පූර්ණ නම",
    formFullNamePlaceholder: "ඔබේ සම්පූර්ණ නම ඇතුළත් කරන්න",
    formEmail: "ඊමේල් ලිපිනය",
    formEmailPlaceholder: "your@email.com",
    formDistrictLive: "ඔබ ජීවත් වන දිස්ත්‍රික්කය",
    formSelectDistrictOpt: "— ඔබේ දිස්ත්‍රික්කය තෝරන්න —",
    formBtnRegister: "අනතුරු ඇඟවීම් සඳහා ලියාපදිංචි වන්න",
    formPrivacyNote: "ඔබගේ තොරතුරු භාවිතා කරනුයේ ප්‍රජා කාලගුණ අනතුරු ඇඟවීම් යැවීමට පමණි",

    registerTitle: "ලියාපදිංචි වන්න",
    passwordLabel: "මුරපදය (අකුරු 6+)",
    selectDistrict: "-- ඔබේ දිස්ත්‍රික්කය තෝරන්න --",
    creatingAccount: "ගිණුම සකසමින්...",
    alreadyHaveAccount: "දැනටමත් ගිණුමක් තිබේද? ",
    loginLink: "ඇතුල් වන්න",
    errSelectCity: "කරුණාකර ඔබේ නගරය තෝරන්න.",
    errPasswordShort: "මුරපදය අවම වශයෙන් අකුරු 6ක් විය යුතුය.",

    reportTitle: "අනතුරු ඇඟවීමක් වාර්තා කරන්න",
    selectDistrictPlaceholder: "දිස්ත්‍රික්කය තෝරන්න",
    selectDistrictAlert: "කරුණාකර ඉදිරිපත් කිරීමට පෙර දිස්ත්‍රික්කයක් තෝරන්න.",
    alertSeverityLabel: "අවදානම් තත්ත්වය",
    medium: "මධ්‍යම",
    normal: "සාමාන්‍ය",
    locationLabel: "ස්ථානය",
    descriptionLabel: "විස්තරය",
    uploadImageLabel: "ඡායාරූපයක් එක් කරන්න (අත්‍යවශ්‍ය නොවේ)",
    selectedPoint: "තෝරාගත් ස්ථානය",
    submittingText: "ඇතුළත් වෙමින් පවතී...",
    submitBtnText: "වාර්තාව ඉදිරිපත් කරන්න",
    mapInstruction: "නිවැරදි ස්ථානය සලකුණු කිරීමට සිතියම මත ක්ලික් කරන්න:",
    reportingForDistrict: "වාර්තා කරන්නේ",
    districtText: "දිස්ත්‍රික්කය සඳහායි",
    alertsText: "වාර්තා",
    alertProgress: "වාර්තා ප්‍රගතිය",
    alertsToday: "අද දින ලැබුණු වාර්තා",
    moreToTrigger: "ඊමේල් යැවීමට තව අවශ්‍යයි",
    oneMoreAlertWarning: "මෙම දිස්ත්‍රික්කයට තවත් එක් වාර්තාවක් ලැබුණු සැනින් සියලුම පදිංචිකරුවන්ට ඊමේල් පණිවිඩයක් නිකුත් වේ!",
    submitSuccess: "වාර්තාව සාර්ථකව ඉදිරිපත් කරන ලදී! ප්‍රජාව දැනුවත් කිරීමට උදව් වීම ගැන ස්තුතියි.",
    emailSentTitle: "ප්‍රජා අනතුරු ඇඟවීමේ ඊමේල් යවන ලදී!",
    registeredResidents: "ප්‍රමාණයක ලියාපදිංචි පදිංචිකරුවන්",
    emailSentDesc: "වෙත මෙම අනතුරු ඇඟවීම පිළිබඳව දැනුම් දී ඇත.",
    somethingWrong: "යම් දෝෂයක් සිදු විය! කරුණාකර නැවත උත්සාහ කරන්න."
  },
  ta: {
    alerts: "எச்சரிக்கைகள்",
    home: "முகப்பு",
    map: "வரைபடம்",
    report: "புகாரளிக்கவும்",
    register: "பதிவு",
    loading: "நேரடி எச்சரிக்கைகள் ஏற்றப்படுகின்றன...",
    noAlerts: "இன்னும் எச்சரிக்கைகள் எதுவும் பதிவாகவில்லை.",
    searchPlaceholder: "தேடவும் (கொழும்பு, யாழ்ப்பாணம், கண்டி)...",
    searchBtn: "தேடு",
    fullName: "முழு பெயர்",
    email: "மின்னஞ்சல் முகவரி",
    district: "உங்கள் மாவட்டம்",
    submit: "சமர்ப்பிக்கவும்",
    mainTitle: "உள்ளூர் வானிலை பாதிப்பு மற்றும் சமூக எச்சரிக்கைகள்",
    subTitle: "உங்கள் பகுதிக்கான நிகழ்நேர வானிலை அறிவிப்புகள் மற்றும் சமூக எச்சரிக்கைகளைப் பெறுங்கள்.",
    selectCity: "ஒரு நகரத்தைத் தேர்ந்தெடுக்கவும்",
    condition: "நிலைமை",
    windSpeed: "காற்றின் வேகம்",
    regionalAlert: "பிராந்திய எச்சரிக்கை",
    alertDesc: "கடலோர மாகாணங்களுக்கு பருவமழை எச்சரிக்கைகள் விடுக்கப்படலாம். உள்ளூர் ஆலோசனைகளைச் சரிபார்க்கவும்.",
    viewDetails: "விவரங்களைப் பார்க்கவும்",

    alertsTitle: "சமூக அறிவிப்புகள்",
    defaultAlertTitle: "சமூக அறிக்கை",
    daysLeftText: "நாட்களில்",
    expiryInfo: "அறிவிப்புகள் தானாகவே நீக்கப்படும் கால அளவு",
    days: "நாட்கள்",
    loadingAlerts: "அறிவிப்புகள் ஏற்றப்படுகின்றன...",
    noAlertsWithSeverity: "இந்த ஆபத்து மட்டத்தில் எந்த அறிவிப்புகளும் இல்லை.",
    submitReportNotice: "அறிக்கையை இங்கே காண ஒரு பதிவைச் சமர்ப்பிக்கவும்.",
    autoDeletesIn: "தானாக நீங்குவதற்கு இன்னும்",
    deleteReportTitle: "அறிக்கையை நீக்கவா?",
    deleteReportDesc: "இந்த சமூக அறிக்கையை நிரந்தரமாக நீக்க விரும்புகிறீர்களா? இந்தச் செயலை மாற்றியமைக்க முடியாது.",
    cancel: "இரத்து செய்",
    deleteBtn: "நீக்கு",
    deletingBtn: "நீக்கப்படுகிறது...",
    districtLabel: "மாவட்டம்",
    justNow: "இப்போது",
    today: "இன்று",
    yesterday: "நேற்று",
    daysAgo: "நாட்களுக்கு முன்",
    highRisk: "அதிதீவிரம்",
    mediumRisk: "மத்திமம்",
    normalRisk: "சாதாரண நிலை",
    confirmedStatus: "உறுதிப்படுத்தப்பட்டது",
    pendingStatus: "செயலாக்கத்தில்",
    reportsCount: "அறிக்கைகள்",
    reportsToday: "இன்றைய அறிக்கைகள்",

    districtAlertTitle: "மாவட்ட எச்சரிக்கை பதிவு",
    districtAlertSub: "உங்கள் மாவட்டத்தில் 3+ அறிக்கைகள் சமர்ப்பிக்கப்படும் போது சமூக எச்சரிக்கை மின்னஞ்சல்களைப் பெற பதிவு செய்யவும்",
    totalRegistered: "மொத்தம் பதிவு செய்யப்பட்டவை",
    activeEmails: "செயலில் உள்ள மின்னஞ்சல்கள்",
    districtsCovered: "உள்ளடக்கப்பட்ட மாவட்டங்கள்",
    selectDistrictCard: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    topDistrictsTitle: "அதிகம் பதிவு செய்யப்பட்ட மாவட்டங்கள்",
    
    formTitle: "எச்சரிக்கைகளுக்கு பதிவு செய்யவும்",
    formFullName: "முழு பெயர்",
    formFullNamePlaceholder: "உங்கள் முழு பெயரை உள்ளிடவும்",
    formEmail: "மின்னஞ்சல் முகவரி",
    formEmailPlaceholder: "your@email.com",
    formDistrictLive: "நீங்கள் வசிக்கும் மாவட்டம்",
    formSelectDistrictOpt: "— உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும் —",
    formBtnRegister: "எச்சரிக்கைகளுக்கு பதிவு செய்யவும்",
    formPrivacyNote: "உங்கள் தகவல்கள் சமூக வானிலை எச்சரிக்கைகளை அனுப்ப மட்டுமே பயன்படுத்தப்படும்",

    registerTitle: "பதிவு செய்க",
    passwordLabel: "கடவுச்சொல் (6+ எழுத்துக்கள்)",
    selectDistrict: "-- உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும் --",
    creatingAccount: "கணக்கு உருவாக்கப்படுகிறது...",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா? ",
    loginLink: "உள்நுழைக",
    errSelectCity: "தயவுசெய்து உங்கள் நகரத்தைத் தேர்ந்தெடுக்கவும்.",
    errPasswordShort: "கடவுச்சொல் குறைந்தது 6 எழுத்துக்களாக இருக்க வேண்டும்.",

    reportTitle: "ஒரு எச்சரிக்கையைப் புகாரளிக்கவும்",
    selectDistrictPlaceholder: "மாவட்டத்தைத் தேர்ந்தெடுக்கவும்",
    selectDistrictAlert: "சமர்ப்பிப்பதற்கு முன் தயவுசெய்து ஒரு மாவட்டத்தைத் தேர்ந்தெடுக்கவும்.",
    alertSeverityLabel: "அபாய நிலை",
    medium: "மத்தியமம்",
    normal: "சாதாரணமானது",
    locationLabel: "இடம்",
    descriptionLabel: "விளக்கம்",
    uploadImageLabel: "புகைப்படத்தைப் பதிவேற்றவும் (விருப்பத்திற்குரியது)",
    selectedPoint: "தேர்ந்தெடுக்கப்பட்ட புள்ளி",
    submittingText: "சமர்ப்பிக்கப்படுகிறது...",
    submitBtnText: "எச்சரிக்கையைச் சமர்ப்பிக்கவும்",
    mapInstruction: "துல்லியமான இடத்தைக் குறிக்க வரைபடத்தில் கிளிக் செய்யவும்:",
    reportingForDistrict: "புகாரளிக்கப்படும் மாவட்டம்",
    districtText: "மாவட்டம்",
    alertsText: "எச்சரிக்கைகள்",
    alertProgress: "எச்சரிக்கை முன்னேற்றம்",
    alertsToday: "இன்றைய எச்சரிக்கைகள்",
    moreToTrigger: "மின்னஞ்சலை அனுப்ப இன்னும் தேவை",
    oneMoreAlertWarning: "இந்த மாவட்டத்தில் இன்னும் ஒரு எச்சரிக்கை பதிவானால், பதிவுசெய்த அனைத்து குடியிருப்பாளர்களுக்கும் மின்னஞ்சல் அறிவிப்பு அனுப்பப்படும்!",
    submitSuccess: "எச்சரிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது! உங்கள் சமூகத்திற்கு உதவியதற்கு நன்றி.",
    emailSentTitle: "சமூக எச்சரிக்கை மின்னஞ்சல்கள் அனுப்பப்பட்டன!",
    registeredResidents: "பதிவுசெய்யப்பட்ட குடியிருப்பாளர்கள்",
    emailSentDesc: "ஆகியோருக்கு இந்த எச்சரிக்கை குறித்து அறிவிக்கப்பட்டுள்ளது.",
    somethingWrong: "ஏதோ தவறு நடந்துவிட்டது! தயவுசெய்து மீண்டும் முயற்சிக்கவும்."
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // 🌟 LocalStorage එකෙන් කලින් තෝරපු භාෂාව කියවා ගනී, නැතහොත් default ලෙස 'en' ලබා ගනී
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('app_lang') || 'en';
  }); 

  // 🌟 භාෂාව වෙනස් වන සෑම විටම එය local storage එකෙහි තැන්පත් කරයි
  useEffect(() => {
    localStorage.setItem('app_lang', lang);
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);